# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42b7733a7b47aa6bb459c8c72ea42fc6760ae1f154c0a0194ea27862f92092c42bc3bef756fc1f310387a3cd2e1f45fdad2be149907d0d44cb109f6734f39af4

test:
  secret_key_base: 7076cc19faa7320a016a473394e0e726b2b389ecd845bc9a383d93151fa519702e69b2fac8d02ec67041f04424d3e8b755ecc7bf59d463a52905f3b5236147bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
